# Generated by Django 4.2.2 on 2024-04-02 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=1)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='mom/items/')),
                ('is_available', models.BooleanField(default=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='mom.menu')),
            ],
        ),
        migrations.CreateModel(
            name='MomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitchen_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=10)),
                ('cuisine_type', models.CharField(blank=True, max_length=200)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='mom/profile/')),
                ('banenr', models.ImageField(blank=True, null=True, upload_to='mom/banner/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_address', models.CharField(blank=True, max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='customer.customer')),
                ('items', models.ManyToManyField(to='mom.menuitem')),
                ('moms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moms', to='mom.mommodel')),
            ],
        ),
        migrations.CreateModel(
            name='OrderAccept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ordered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('total_price', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('preparing', 'preparing'), ('On the Way', 'On the Way'), ('delivered', 'delivered'), ('canceled', 'canceled')], default='not ordered', max_length=20)),
                ('is_delivered', models.BooleanField(default=False)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item', to='mom.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='mom.order')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(blank=True, max_length=200)),
                ('total_amount', models.DecimalField(decimal_places=3, max_digits=8)),
                ('order_accept', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_order_accept', to='mom.orderaccept')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('moms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mom.mommodel')),
            ],
        ),
        migrations.CreateModel(
            name='Recipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipt_name', models.CharField(blank=True, max_length=200, null=True)),
                ('paid_amount', models.IntegerField(default=0)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_recipt', to='mom.payment')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPlaced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_placed', models.BooleanField(default=False)),
                ('order_placed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_placed', to='mom.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='OrderAcceptNotifcation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_order_accept_customer', to='customer.customer')),
                ('mom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_order_accept_mom', to='mom.mommodel')),
                ('order_accept', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mom.orderaccept')),
                ('ordered_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_accept', to='mom.orderitem')),
            ],
        ),
        migrations.AddField(
            model_name='orderaccept',
            name='order_placed',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_placed_accept', to='mom.orderplaced'),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('moms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mom.mommodel')),
            ],
        ),
        migrations.CreateModel(
            name='Notifcation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_cust', to='customer.customer')),
                ('mom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_mom', to='mom.mommodel')),
                ('order_placed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_placed_notification', to='mom.orderplaced')),
            ],
        ),
        migrations.CreateModel(
            name='MomsStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_review', models.IntegerField()),
                ('average_rating', models.FloatField()),
                ('moms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mom.mommodel')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='moms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='momsmenu', to='mom.mommodel'),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.CharField(blank=True, max_length=200)),
                ('delivery_status', models.CharField(default='Pending', max_length=200)),
                ('delivery_person', models.CharField(blank=True, max_length=200)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mom.order')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mom.cart')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mom.menuitem')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(through='mom.CartItem', to='mom.menuitem'),
        ),
    ]
